### ISSUE TITLE
[PLUG-FE] Sandbox환경 상호작용

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Plugin-Client#17]
## 이슈 사항
유저가 rect요소를 클릭 했을 시 해당 rect가 갖고있는 변경사항 정보를 가져올 수 있어야 합니다.
변경사항 정보를 가져 온 뒤, postMessage를 통해서 UI에게 해당 정보를 전달 할 수 있어야 합니다.

<br />

## Todo 리스트
- [x] 유저가 rect를 클릭한것을 인식하고, 해당 rect가 갖고있는 데이터를 가져와야 합니다.
- [x] 클릭한 요소에 대하여 데이터를 가져 온 뒤, 해당 데이터의 내용을 Difference컴포넌트에게 전달해주어야 합니다. (`"RENDER_DIFFERENCE_INFORMATION"`)
- [x] 페이지가 변경됨에 따라 변경 된 페이지의 아이디를 Difference컴포넌트에게 전달해주어야 합니다.
(`"CHANGED_CURRENT_PAGE_ID"`)

<br />
