### ISSUE TITLE
[PLUG-FE] Page변경에 따른 UI 로직

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Plugin-Client#19]
## 이슈 사항
1. `sandbox`로부터 `pageId`가 넘어오게 되면 현재 버전과 이전 버전의 공통페이지 인지 검사를 해야 합니다.
**_❗️이 때 `sandbox`로부터 변경사항을 받게되어서 리렌더링이 될 때에는 쿼리요청이 진행되면 안됩니다._**
2. 공통페이지라면 `react-query`를 이용하여 변경된 `pageId`에 대한 `diffingResult`를 받아와야 합니다.
3. 이후 postMessage를 활용해 `"POST_DIFFING_RESULT"` 라는 타입으로 `sandbox`에게 렌더에 필요한 정보를 보내주어야 합니다.
4. 공통페이지가 아니라면 UI에 토스트 메세지를 띄워야 합니다.

<br />

## Todo 리스트
> 이슈를 위해 해야할 일을 정리해주세요!

- [ ] sandbox로부터 바뀐 pageId를 받아오는 이벤트 핸들러 함수가 필요 합니다. (`sideEffect` 처리 필수)
- [ ] 변경된 `pageId`에 대해서만 유효성 검사 통과 후 API요청이 이루어 져야 합니다.
- [ ] 최초 변경사항을 `sandbox`에 전달하던 형식과 동일하게 `"POST_DIFFING_RESULT"` type의 `postMessage`를 보내야 합니다.

![image](https://github.com/Figci/Figci-Plugin-Client/assets/48385389/e59323fc-8f30-4c40-afcd-6ece24b71d13)
→ `sandbox`에서 `diffingResult`를 받는 구조
