### ISSUE TITLE
[PLUG_FE] 비교 페이지 - 페이지네이션 구현

### ISSUE THREAD

**Issue by kyeongjun-ko** [Figci/Figci-Plugin-Client#31]
## 이슈 사항
1. 3차 발표 피드백에 따라 사용 방법이 어렵다는 피드백을 반영하기 위해서
사용자 경험을 고려하여서 변경 페이지내에 페이지네이션 기능을 구현한다.

사용자는 현재 변경된 요소의 갯수와 현재 선택한 변경요소의 숫자를 알수 있고
버튼을 사용하여 다음 변경된 요소를 확인 할 수 있다.

<br />

## Todo 리스트

1. 기능 추가에 따른 디자인 변경사항 반영하기

| 변경 전 | 변경 후 |
| ---- | ---- |
|![image](https://github.com/Figci/Figci-Plugin-Client/assets/95596243/4de69ab9-f4a7-400f-bd4a-c29407f24fc5)|![image](https://github.com/Figci/Figci-Plugin-Client/assets/95596243/7d6658fc-7ee0-4996-961b-94841e80a2a7)|

- 레이아웃
 - [x] 버전 재선택 버튼 레이아웃 변경 - 헤더바 고정
 - [x] 페이지 네이션 레이아웃 - 정보, 버튼

- 기능구현
 - [x] 페이지네이션 버튼 클릭 시 다음 변경 노드 화면 포커스
 - [x] 변경 결과 존재 여부에 따라 페이지네이션 버튼 비활성화
 - [x] 변경 노드 렌더시 첫번째 변경 노드 위치 화면 포커스

<br />
